# apiVersion: v1
# kind: Pod
# metadata:
#   name: my-nginx-pod
#   namespace: my-namespace
# spec:
#   containers:
#   - name: my-nginx-pod
#     image: registry.cluster.wik.cloud/public/echo
#     ports:
#     - containerPort: 8080



# apiVersion: apps/v1
# kind: ReplicaSet
# metadata:
#   name: my-nginx-replicaset
#   namespace: my-namespace
# spec:
#   replicas: 4
#   selector:
#     matchLabels:
#       app: my-nginx
#   template:
#     metadata:
#       labels:
#         app: my-nginx
#     spec:
#       containers:
#       - name: my-nginx-pod
#         image: registry.cluster.wik.cloud/public/echo
#         ports:
#         - containerPort: 8080



# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: my-nginx-deployment
#   namespace: my-namespace
# spec:
#   replicas: 4
#   selector:
#     matchLabels:
#       app: my-nginx
#   template:
#     metadata:
#       labels:
#         app: my-nginx
#     spec:
#       containers:
#       - name: my-nginx-pod
#         image: registry.cluster.wik.cloud/public/echo
#         ports:
#         - containerPort: 8080
#   strategy:
#     type: RollingUpdate
#     rollingUpdate:
#       maxUnavailable: 50%



apiVersion: v1
kind: Service
metadata:
  name: my-nginx-service
  namespace: my-namespace
spec:
  selector:
    app: my-nginx
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080



