apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myingress
  namespace: tp04
  labels:
    name: myingress
spec:
  rules:
  - host: tp04.local
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: myapp-service
            port: 
              number: 45129

---

apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  namespace: tp04
  labels:
    name: myapp
spec:
  selector:
    app: myapp
  ports:
    - port: 45129
      targetPort: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: tp04
  labels:
    name: myapp-deployment
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 4
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: registry.cluster.wik.cloud/public/echo
        ressources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080